language: cpp
dist: xenial

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-8
    packages:
      - cmake
      - clang-8
      - clang-format-8

install:
  # Install Gtest
  - sudo wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz
  - sudo tar xf release-1.8.1.tar.gz
  - cd googletest-release-1.8.1
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make -j8
  - sudo cp -a googletest/include/gtest /usr/include
  - sudo cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/
  - cd -

before_script:
  - export CC=clang-8
  - export CXX=clang++-8

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./Tests
  - cd ..

matrix:
  include:
    - env: Run Tests
      script:
      - mkdir build
      - cd build
      - cmake ..
      - make -j8
      - ./Tests
      - cd ..
    - env: 
      script: Clang Format Check
      - ./scripts/run-clang-format/run-clang-format.py -r src test
