language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - g++-9
      - gcc-9
      - cmake
      - clang-8
      - clang-format-8

install:
  # Install Gtest
  - sudo wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz
  - sudo tar xf release-1.8.1.tar.gz
  - cd googletest-release-1.8.1
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make -j8
  - sudo cp -a googletest/include/gtest /usr/include
  - sudo cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/
  - cd -

before_script:
  - export CC=clang-8 && export CXX=clang++-8

matrix:
  include:
    - env: Run Tests
      before_script:
        - export CC=clang-8 && export CXX=clang++-8
      script:
        - mkdir build && cd build
        - cmake .. && make -j8
        - ./Tests
    - env: Clang Format Check
      before_script:
        - export CC=gcc-9 && export CXX=g++-9
      script: 
        - ./clang-check/run-clang-format.py -r src test
