language: cpp
dist: xenial

addons:
  apt:
    sources:
      - llvm-toolchain-xenial-7
    packages:
      - cmake
      - clang-7
      - clang-format-7

install:
  # Install Gtest
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make -j8
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - cd -

before_script:
  - export CC=clang-7
  - export CXX=clang++-7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./Tests
  - cd ..
