set(PCRE2_SUPPORT_JIT AUTO)
set(PCRE2_BUILD_PCRE2_32 ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

add_subdirectory(3rd/pcre2 EXCLUDE_FROM_ALL)
set(PCRE2_INCLUDE_DIR ${CMAKE_BINARY_DIR}/pcre2/)
set(PCRE2_LIB pcre2-32)

include_directories(${PCRE2_INCLUDE_DIR})
